import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from './provider'
import { Toaster } from "@/components/ui/sonner";
import { MantineProvider } from "@mantine/core";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ai Voice Recruiter",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MantineProvider withGlobalStyles withNormalizeCSS>
          <Provider>
            {children}
            <Toaster />
          </Provider>
        </MantineProvider>
      </body>
    </html>
  );
}
